import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageType = 'en' | 'hi' | 'ta' | 'kn' | 'gu' | 'bn';

interface LanguageContextType {
  language: LanguageType;
  setLanguage: (lang: LanguageType) => void;
  t: (key: string) => string;
}

const translations: Record<LanguageType, Record<string, string>> = {
  en: {
    home: 'Home',
    philosophy: 'Philosophy',
    database: 'Database',
    search: 'Search',
    dashboard: 'Dashboard',
    signin: 'Sign In',
    signup: 'Sign Up',
    welcome: 'Welcome',
    logout: 'Logout',
    madeWith: 'MADE WITH <3 by TEAM BOOMERS',
    madeByIndians: 'MADE BY INDIANS FOR INDIANS',
    heroTitle: 'THE future OF MEDICINE.',
    heroSubtitle: 'AI-POWERED DIAGNOSIS & MEDICINE DATABASE',
    searchMedicine: 'Search Medicine',
    adminAccess: 'Admin Access',
    userAccess: 'User Access Demo',
    googleLogin: 'Google Login',
    createAccount: 'Create Account',
    accessAccount: 'Access Account',
    myPrescriptions: 'My Prescriptions',
    healthHistory: 'Health History',
    savedItems: 'Saved Items',
    quickStats: 'Quick Stats',
    heartRate: 'Heart Rate',
    bloodPressure: 'Blood Pressure',
    nextRefill: 'Next Refill',
    reschedule: 'Reschedule',
    findInfo: 'Find information, dosage, and side effects instantly',
    hello: 'Hello',
    healthHub: 'Your Health Hub',
    adminDashboard: 'Admin Dashboard',
    totalUsers: 'Total Users',
    activeSessions: 'Active Sessions',
    databaseSize: 'Database Size',
    systemStatus: 'System Status',
    recentActivity: 'Recent Activity',
    quickActions: 'Quick Actions',
    manageUsers: 'Manage Users',
    editDatabase: 'Edit Database',
    viewReports: 'View Reports',
    systemSettings: 'System Settings',
    philosophyTitle: 'We believe that transparency is the first step towards a healthier society. MedAI is not just a tool; it\'s a movement to democratize medical knowledge.',
    philosophyLabel: 'OUR PHILOSOPHY',
    realWorldExp: 'REAL-WORLD EXPERIENCE',
    realWorldDesc: 'WE DON\'T JUST SHOW YOU DATA; WE PROVIDE CONTEXT FROM REAL-WORLD CLINICAL TRIALS AND PATIENT OUTCOMES.',
    profMentorship: 'PROFESSIONAL MENTORSHIP',
    profDesc: 'OUR PLATFORM IS BUILT WITH INPUT FROM TOP MEDICAL PROFESSIONALS TO ENSURE ACCURACY AND RELIABILITY.',
    comparisonTitle: 'TRADITIONAL VS MEDAI',
    tradLabel: 'TRADITIONAL',
    medaiLabel: 'MEDAI',
    tradPoint1: 'Opaque pricing and hidden costs',
    tradPoint2: 'Limited access to clinical data',
    tradPoint3: 'Slow, manual comparison process',
    medaiPoint1: 'Complete transparency in every pill',
    medaiPoint2: 'AI-driven insights from global trials',
    medaiPoint3: 'Instant, accurate data at your fingertips',
    searchPlaceholder: 'Search for a medicine (e.g., Paracetamol)...',
    dosage: 'Dosage',
    sideEffects: 'Side Effects',
    interactions: 'Interactions',
    viewDetails: 'View Details',
    project: 'Project',
    status: 'Status',
    active: 'ACTIVE',
    scrollToExplore: 'Scroll to explore',
    orContinueWith: 'Or continue with',
    newToPlatform: 'New to the platform?',
    alreadyHaveAccount: 'Already have an account?',
    databaseLabel: 'DATABASE',
    accessPortal: 'ACCESS PORTAL',
    databaseDesc: 'Our complete analytical database is now open for public research. Compare thousands of branded medicines with their generic equivalents.',
    readyForAnalysis: 'Ready for analysis',
    exploreFullArchive: 'EXPLORE THE FULL ARCHIVE.',
    enterDatabase: 'Enter Database',
    medicines: 'Medicines',
    verified: 'Verified',
    avgSavings: 'Avg. Savings',
    systemStatusOperational: 'System Status: Operational',
    copyrightMedAI: '© 2026 MedAI Analytical Unit',
    searchEngine: 'SEARCH ENGINE.',
    inputQuery: 'INPUT QUERY',
    enterMedicineName: 'Enter medicine name...',
    noResultsFound: 'No results found in database',
    readyForAnalysisSearch: 'READY FOR ANALYSIS',
    selectMedicineToBegin: 'Select a medicine from the sidebar to begin',
    brandedStandard: 'Branded Standard',
    genericAlternative: 'Generic Alternative',
    verifiedEquivalent: 'Verified Equivalent',
    marketPrice: 'Market Price',
    ourPrice: 'Our Price',
    savings: 'Savings',
    costAnalysis: 'Cost Analysis',
    composition: 'Composition',
    molecularStructureIdentical: 'Molecular structure and active ingredients are 100% identical to the branded version.',
    generatePrescriptionReport: 'Generate Prescription Report',
    analyticalDatabaseVersion: 'Analytical Database v2.0',
    description: 'Description',
    switchingTo: 'Switching to',
    savesYouApproximately: 'saves you approximately',
    perUnit: 'per unit.',
    footerDesc: 'A project dedicated to transparency in healthcare. Built for the future of medicine.',
    navigation: 'Navigation',
    socials: 'Socials',
    madeInAugust: 'MADE IN AUGUST®',
    operational: 'Operational',
    live: 'Live',
    viewAll: 'View All',
    patientRecord: 'Patient Record',
    analyzed2HoursAgo: 'Analyzed 2 hours ago',
    aiConfidence: 'AI Confidence',
    healthTrendsVisualization: 'Health Trends Visualization',
    realTimeDataProcessing: 'Real-time data processing...',
    upcomingAppointments: 'Upcoming Appointments',
    staffMeeting: 'Staff Meeting',
    conferenceRoomB: 'Conference Room B',
    accessFeature: 'Access Feature',
    myPrescriptionsDesc: 'Keep track of your current medications and schedules.',
    healthHistoryDesc: 'View your past diagnoses and medical reports.',
    savedItemsDesc: 'Quick access to your bookmarked medicines and articles.',
    generalCheckup: 'General Checkup',
    drSarahJohnson: 'Dr. Sarah Johnson',
    in4Days: 'In 4 Days',
    genericComparator: 'GENERIC COMPARATOR',
    rxScanner: 'Rx Scanner',
    pharmacy: 'Pharmacy',
    details: 'Details',
    findAffordableGenericMedicines: 'Find Affordable Generic Medicines',
    discoverWhoApproved: 'Discover WHO-approved generic alternatives to expensive branded medicines. Same efficacy, fraction of the cost.',
    searchBrandName: 'Search brand name, generic, or composition...',
    medicinesListed: 'Medicines Listed',
    averageSavings: 'Average Savings',
    popularMedicines: 'Popular Medicines',
    branded: 'Branded',
    generic: 'Generic',
    youSave: 'YOU SAVE',
    medicalUsage: 'MEDICAL USAGE',
    about: 'ABOUT',
    similarMedicines: 'Similar Medicines',
    aiRecommendations: 'AI Recommendations',
    poweredByGpt4o: 'Powered by GPT-4o',
    nearestPharmacies: 'Nearest Pharmacies',
    findRealNearbyChemists: 'Find real nearby chemists using your live location.',
    allowLocationAccess: 'Allow Location Access',
    shareYourLocation: 'Share your location to discover real pharmacies near you on a live map.',
    shareMyLocation: 'Share My Location',
    analyzeAndFindGenerics: 'Analyze & Find Generics',
    uploadPrescription: 'Upload Prescription',
    clickToUpload: 'Click to upload a photo or scan (JPG, PNG, PDF)',
    orTypeBelow: 'OR TYPE BELOW',
    typeMedicineNames: 'Type medicine names, e.g. Crocin 500, Augmentin 625...',
    backToSearch: 'Back to Search',
    priceComparison: 'PRICE COMPARISON',
    perStrip: 'per strip',
    genericPriceVsBranded: 'Generic price vs branded',
  },
  hi: {
    home: 'होम',
    philosophy: 'दर्शन',
    database: 'डेटाबेस',
    search: 'खोजें',
    dashboard: 'डैशबोर्ड',
    signin: 'साइन इन',
    signup: 'साइन अप',
    welcome: 'स्वागत है',
    logout: 'लॉगआउट',
    madeWith: 'टीम बूमर्स द्वारा <3 के साथ बनाया गया',
    madeByIndians: 'भारतीयों द्वारा भारतीयों के लिए बनाया गया',
    heroTitle: 'किफायती चिकित्सा का भविष्य।',
    heroSubtitle: 'एआई-संचालित निदान और चिकित्सा डेटाबेस',
    searchMedicine: 'दवा खोजें',
    adminAccess: 'एडमिन एक्सेस',
    userAccess: 'यूजर एक्सेस डेमो',
    googleLogin: 'गूगल लॉगिन',
    createAccount: 'खाता बनाएं',
    accessAccount: 'खाता एक्सेस करें',
    myPrescriptions: 'मेरे नुस्खे',
    healthHistory: 'स्वास्थ्य इतिहास',
    savedItems: 'सहेजे गए आइटम',
    quickStats: 'त्वरित आँकड़े',
    heartRate: 'हृदय गति',
    bloodPressure: 'रक्तचाप',
    nextRefill: 'अगला रिफिल',
    reschedule: 'पुनर्निर्धारित करें',
    findInfo: 'तुरंत जानकारी, खुराक और दुष्प्रभाव खोजें',
    hello: 'नमस्ते',
    healthHub: 'आपका स्वास्थ्य केंद्र',
    adminDashboard: 'एडमिन डैशबोर्ड',
    totalUsers: 'कुल उपयोगकर्ता',
    activeSessions: 'सक्रिय सत्र',
    databaseSize: 'डेटाबेस आकार',
    systemStatus: 'सिस्टम स्थिति',
    recentActivity: 'हाल की गतिविधि',
    quickActions: 'त्वरित कार्रवाइयां',
    manageUsers: 'उपयोगकर्ता प्रबंधित करें',
    editDatabase: 'डेटाबेस संपादित करें',
    viewReports: 'रिपोर्ट देखें',
    systemSettings: 'सिस्टम सेटिंग्स',
    philosophyTitle: 'हमारा मानना है कि पारदर्शिता एक स्वस्थ समाज की ओर पहला कदम है। मेडएआई सिर्फ एक उपकरण नहीं है; यह चिकित्सा ज्ञान को लोकतांत्रिक बनाने का एक आंदोलन है।',
    philosophyLabel: 'हमारा दर्शन',
    realWorldExp: 'वास्तविक दुनिया का अनुभव',
    realWorldDesc: 'हम आपको केवल डेटा नहीं दिखाते हैं; हम वास्तविक दुनिया के नैदानिक परीक्षणों और रोगी परिणामों से संदर्भ प्रदान करते हैं।',
    profMentorship: 'पेशेवर मार्गदर्शन',
    profDesc: 'सटीकता और विश्वसनीयता सुनिश्चित करने के लिए हमारा प्लेटफॉर्म शीर्ष चिकित्सा पेशेवरों के इनपुट के साथ बनाया गया है।',
    comparisonTitle: 'पारंपरिक बनाम मेडएआई',
    tradLabel: 'पारंपरिक',
    medaiLabel: 'मेडएआई',
    tradPoint1: 'अपारदर्शी मूल्य निर्धारण और छिपी हुई लागत',
    tradPoint2: 'नैदानिक डेटा तक सीमित पहुंच',
    tradPoint3: 'धीमी, मैन्युअल तुलना प्रक्रिया',
    medaiPoint1: 'हर गोली में पूर्ण पारदर्शिता',
    medaiPoint2: 'वैश्विक परीक्षणों से एआई-संचालित अंतर्दृष्टि',
    medaiPoint3: 'आपकी उंगलियों पर त्वरित, सटीक डेटा',
    searchPlaceholder: 'दवा खोजें (जैसे, पैरासिटामोल)...',
    dosage: 'खुराक',
    sideEffects: 'दुष्प्रभाव',
    interactions: 'पारस्परिक क्रिया',
    viewDetails: 'विवरण देखें',
    project: 'परियोजना',
    status: 'स्थिति',
    active: 'सक्रिय',
    scrollToExplore: 'एक्सप्लोर करने के लिए स्क्रॉल करें',
    orContinueWith: 'या इसके साथ जारी रखें',
    newToPlatform: 'प्लेटफॉर्म पर नए हैं?',
    alreadyHaveAccount: 'क्या आपके पास पहले से खाता है?',
    databaseLabel: 'डेटाबेस',
    accessPortal: 'एक्सेस पोर्टल',
    databaseDesc: 'हमारा संपूर्ण विश्लेषणात्मक डेटाबेस अब सार्वजनिक शोध के लिए खुला है। हजारों ब्रांडेड दवाओं की उनके जेनेरिक समकक्षों के साथ तुलना करें।',
    readyForAnalysis: 'विश्लेषण के लिए तैयार',
    exploreFullArchive: 'पूरा संग्रह देखें।',
    enterDatabase: 'डेटाबेस में प्रवेश करें',
    medicines: 'दवाएं',
    verified: 'सत्यापित',
    avgSavings: 'औसत बचत',
    systemStatusOperational: 'सिस्टम स्थिति: चालू',
    copyrightMedAI: '© 2026 मेडएआई विश्लेषणात्मक इकाई',
    searchEngine: 'खोज इंजन।',
    inputQuery: 'इनपुट क्वेरी',
    enterMedicineName: 'दवा का नाम दर्ज करें...',
    noResultsFound: 'डेटाबेस में कोई परिणाम नहीं मिला',
    readyForAnalysisSearch: 'विश्लेषण के लिए तैयार',
    selectMedicineToBegin: 'शुरू करने के लिए साइडबार से एक दवा चुनें',
    brandedStandard: 'ब्रांडेड मानक',
    genericAlternative: 'जेनेरिक विकल्प',
    verifiedEquivalent: 'सत्यापित समकक्ष',
    marketPrice: 'बाजार मूल्य',
    ourPrice: 'हमारी कीमत',
    savings: 'बचत',
    costAnalysis: 'लागत विश्लेषण',
    composition: 'संरचना',
    molecularStructureIdentical: 'आणविक संरचना और सक्रिय तत्व ब्रांडेड संस्करण के 100% समान हैं।',
    generatePrescriptionReport: 'नुस्खा रिपोर्ट तैयार करें',
    analyticalDatabaseVersion: 'विश्लेषणात्मक डेटाबेस v2.0',
    description: 'विवरण',
    switchingTo: 'पर स्विच करना',
    savesYouApproximately: 'आपको लगभग बचाता है',
    perUnit: 'प्रति यूनिट।',
    footerDesc: 'स्वास्थ्य सेवा में पारदर्शिता के लिए समर्पित एक परियोजना। चिकित्सा के भविष्य के लिए निर्मित।',
    navigation: 'नेविगेशन',
    socials: 'सोशल',
    madeInAugust: 'मेड इन अगस्त®',
    operational: 'चालू',
    live: 'लाइव',
    viewAll: 'सभी देखें',
    patientRecord: 'रोगी रिकॉर्ड',
    analyzed2HoursAgo: '2 घंटे पहले विश्लेषण किया गया',
    aiConfidence: 'एआई विश्वास',
    healthTrendsVisualization: 'स्वास्थ्य रुझान विज़ुअलाइज़ेशन',
    realTimeDataProcessing: 'वास्तविक समय डेटा प्रसंस्करण...',
    upcomingAppointments: 'आगामी नियुक्तियां',
    staffMeeting: 'स्टाफ मीटिंग',
    conferenceRoomB: 'कॉन्फ्रेंस रूम बी',
    accessFeature: 'एक्सेस फीचर',
    myPrescriptionsDesc: 'अपनी वर्तमान दवाओं और शेड्यूल पर नज़र रखें।',
    healthHistoryDesc: 'अपने पिछले निदान और चिकित्सा रिपोर्ट देखें।',
    savedItemsDesc: 'अपनी बुकमार्क की गई दवाओं और लेखों तक त्वरित पहुँच।',
    generalCheckup: 'सामान्य चेकअप',
    drSarahJohnson: 'डॉ. सारा जॉनसन',
    in4Days: '4 दिनों में',
  },
  ta: {
    home: 'முகப்பு',
    philosophy: 'தத்துவம்',
    database: 'தரவுத்தளம்',
    search: 'தேடல்',
    dashboard: 'டாஷ்போர்டு',
    signin: 'உள்நுழை',
    signup: 'பதிவு செய்',
    welcome: 'வரவேற்பு',
    logout: 'வெளியேறு',
    madeWith: 'டீம் பூமரால் <3 உடன் உருவாக்கப்பட்டது',
    madeByIndians: 'இந்தியர்களால் இந்தியர்களுக்காக உருவாக்கப்பட்டது',
    heroTitle: 'மருத்துவத்தின் எதிர்காலம் இங்கே உள்ளது.',
    heroSubtitle: 'AI-இயங்கும் நோய் கண்டறிதல் மற்றும் மருந்து தரவுத்தளம்',
    searchMedicine: 'மருந்து தேடல்',
    adminAccess: 'நிர்வாக அணுகல்',
    userAccess: 'பயனர் அணுகல் டெமோ',
    googleLogin: 'கூகிள் உள்நுழைவு',
    createAccount: 'கணக்கை உருவாக்கு',
    accessAccount: 'கணக்கை அணுகவும்',
    myPrescriptions: 'எனது மருந்துகள்',
    healthHistory: 'சுகாதார வரலாறு',
    savedItems: 'சேமிக்கப்பட்டவை',
    quickStats: 'விரைவான புள்ளிவிவரங்கள்',
    heartRate: 'இதய துடிப்பு',
    bloodPressure: 'இரத்த அழுத்தம்',
    nextRefill: 'அடுத்த நிரப்புதல்',
    reschedule: 'மறுசீரமைக்கவும்',
    findInfo: 'தகவல், அளவு மற்றும் பக்க விளைவுகளை உடனடியாகக் கண்டறியவும்',
    hello: 'வணக்கம்',
    healthHub: 'உங்கள் சுகாதார மையம்',
    adminDashboard: 'நிர்வாக டாஷ்போர்டு',
    totalUsers: 'மொத்த பயனர்கள்',
    activeSessions: 'செயலில் உள்ள அமர்வுகள்',
    databaseSize: 'தரவுத்தள அளவு',
    systemStatus: 'கணினி நிலை',
    recentActivity: 'சமீபத்திய செயல்பாடு',
    quickActions: 'விரைவான செயல்கள்',
    manageUsers: 'பயனர்களை நிர்வகி',
    editDatabase: 'தரவுத்தளத்தைத் திருத்து',
    viewReports: 'அறிக்கைகளைப் பார்',
    systemSettings: 'கணினி அமைப்புகள்',
    philosophyTitle: 'வெளிப்படைத்தன்மை என்பது ஆரோக்கியமான சமூகத்தை நோக்கிய முதல் படி என்று நாங்கள் நம்புகிறோம். மெட்ஏஐ என்பது ஒரு கருவி மட்டுமல்ல; இது மருத்துவ அறிவை ஜனநாயகப்படுத்துவதற்கான ஒரு இயக்கம்.',
    philosophyLabel: 'எங்கள் தத்துவம்',
    realWorldExp: 'நிஜ உலக அனுபவம்',
    realWorldDesc: 'நாங்கள் உங்களுக்கு தரவை மட்டும் காண்பிக்கவில்லை; நிஜ உலக மருத்துவ பரிசோதனைகள் மற்றும் நோயாளி முடிவுகளிலிருந்து சூழலை வழங்குகிறோம்.',
    profMentorship: 'தொழில்முறை வழிகாட்டுதல்',
    profDesc: 'துல்லியம் மற்றும் நம்பகத்தன்மையை உறுதிப்படுத்த சிறந்த மருத்துவ நிபுணர்களின் உள்ளீட்டுடன் எங்கள் தளம் உருவாக்கப்பட்டுள்ளது.',
    comparisonTitle: 'பாரம்பரியம் VS மெட்ஏஐ',
    tradLabel: 'பாரம்பரியம்',
    medaiLabel: 'மெட்ஏஐ',
    tradPoint1: 'மறைமுக விலை நிர்ணயம் மற்றும் மறைக்கப்பட்ட செலவுகள்',
    tradPoint2: 'மருத்துவ தரவுகளுக்கான வரையறுக்கப்பட்ட அணுகல்',
    tradPoint3: 'மெதுவான, கையேடு ஒப்பீட்டு செயல்முறை',
    medaiPoint1: 'ஒவ்வொரு மாத்திரையிலும் முழுமையான வெளிப்படைத்தன்மை',
    medaiPoint2: 'உலகளாவிய சோதனைகளிலிருந்து AI-உந்துதல் நுண்ணறிவு',
    medaiPoint3: 'உங்கள் விரல் நுனியில் உடனடி, துல்லியமான தரவு',
    searchPlaceholder: 'மருந்தைத் தேடுங்கள் (எ.கா., பாராசிட்டமால்)...',
    dosage: 'அளவு',
    sideEffects: 'பக்க விளைவுகள்',
    interactions: 'ஊடாடுதல்',
    viewDetails: 'விவரங்களைக் காண்க',
    project: 'திட்டம்',
    status: 'நிலை',
    active: 'செயலில்',
    scrollToExplore: 'ஆராய உருட்டவும்',
    orContinueWith: 'அல்லது தொடரவும்',
    newToPlatform: 'தளத்திற்கு புதியவரா?',
    alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    databaseLabel: 'தரவுத்தளம்',
    accessPortal: 'அணுகல் போர்டல்',
    databaseDesc: 'எங்கள் முழுமையான பகுப்பாய்வு தரவுத்தளம் இப்போது பொது ஆராய்ச்சிக்கு திறக்கப்பட்டுள்ளது. ஆயிரக்கணக்கான பிராண்டட் மருந்துகளை அவற்றின் பொதுவான சமமானவற்றுடன் ஒப்பிடுங்கள்.',
    readyForAnalysis: 'பகுப்பாய்விற்கு தயார்',
    exploreFullArchive: 'முழு காப்பகத்தையும் ஆராயுங்கள்.',
    enterDatabase: 'தரவுத்தளத்தில் நுழையுங்கள்',
    medicines: 'மருந்துகள்',
    verified: 'சரிபார்க்கப்பட்டது',
    avgSavings: 'சராசரி சேமிப்பு',
    systemStatusOperational: 'கணினி நிலை: செயல்பாட்டில் உள்ளது',
    copyrightMedAI: '© 2026 மெட்ஏஐ பகுப்பாய்வு பிரிவு',
    searchEngine: 'தேடுபொறி.',
    inputQuery: 'உள்ளீட்டு வினவல்',
    enterMedicineName: 'மருந்தின் பெயரை உள்ளிடவும்...',
    noResultsFound: 'தரவுத்தளத்தில் முடிவுகள் எதுவும் இல்லை',
    readyForAnalysisSearch: 'பகுப்பாய்விற்கு தயார்',
    selectMedicineToBegin: 'தொடங்குவதற்கு பக்கவாட்டுப் பட்டியில் இருந்து ஒரு மருந்தைத் தேர்ந்தெடுக்கவும்',
    brandedStandard: 'பிராண்டட் தரநிலை',
    genericAlternative: 'பொதுவான மாற்று',
    verifiedEquivalent: 'சரிபார்க்கப்பட்ட சமமானவை',
    marketPrice: 'சந்தை விலை',
    ourPrice: 'எங்கள் விலை',
    savings: 'சேமிப்பு',
    costAnalysis: 'செலவு பகுப்பாய்வு',
    composition: 'கலவை',
    molecularStructureIdentical: 'மூலக்கூறு அமைப்பு மற்றும் செயலில் உள்ள பொருட்கள் பிராண்டட் பதிப்பிற்கு 100% ஒத்தவை.',
    generatePrescriptionReport: 'மருந்துச் சீட்டு அறிக்கையை உருவாக்கு',
    analyticalDatabaseVersion: 'பகுப்பாய்வு தரவுத்தளம் v2.0',
    description: 'விளக்கம்',
    switchingTo: 'மாற்றுவது',
    savesYouApproximately: 'தோராயமாக உங்களைச் சேமிக்கிறது',
    perUnit: 'ஒரு யூனிட்டுக்கு.',
    footerDesc: 'சுகாதாரப் பாதுகாப்பில் வெளிப்படைத்தன்மைக்காக அர்ப்பணிக்கப்பட்ட ஒரு திட்டம். மருத்துவத்தின் எதிர்காலத்திற்காக கட்டப்பட்டது.',
    navigation: 'வழிசெலுத்தல்',
    socials: 'சமூக வலைதளங்கள்',
    madeInAugust: 'மேட் இன் ஆகஸ்ட்®',
    operational: 'செயல்பாட்டில் உள்ளது',
    live: 'நேரலை',
    viewAll: 'அனைத்தையும் பார்',
    patientRecord: 'நோயாளி பதிவு',
    analyzed2HoursAgo: '2 மணி நேரத்திற்கு முன்பு பகுப்பாய்வு செய்யப்பட்டது',
    aiConfidence: 'AI நம்பிக்கை',
    healthTrendsVisualization: 'சுகாதாரப் போக்குகள் காட்சிப்படுத்தல்',
    realTimeDataProcessing: 'நிகழ்நேர தரவு செயலாக்கம்...',
    upcomingAppointments: 'வரவிருக்கும் சந்திப்புகள்',
    staffMeeting: 'ஊழியர்கள் கூட்டம்',
    conferenceRoomB: 'மாநாட்டு அறை B',
    accessFeature: 'அம்சத்தை அணுகவும்',
    myPrescriptionsDesc: 'உங்கள் தற்போதைய மருந்துகள் மற்றும் அட்டவணைகளைக் கண்காணிக்கவும்.',
    healthHistoryDesc: 'உங்கள் கடந்தகால நோயறிதல்கள் மற்றும் மருத்துவ அறிக்கைகளைப் பார்க்கவும்.',
    savedItemsDesc: 'உங்கள் புக்மார்க் செய்யப்பட்ட மருந்துகள் மற்றும் கட்டுரைகளுக்கான விரைவான அணுகல்.',
    generalCheckup: 'பொது பரிசோதனை',
    drSarahJohnson: 'டாக்டர் சாரா ஜான்சன்',
    in4Days: '4 நாட்களில்',
  },
  kn: {
    home: 'ಮುಖಪುಟ',
    philosophy: 'ತತ್ವಶಾಸ್ತ್ರ',
    database: 'ಡೇಟಾಬೇಸ್',
    search: 'ಹುಡುಕಿ',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    signin: 'ಸೈನ್ ಇನ್',
    signup: 'ಸೈನ್ ಅಪ್',
    welcome: 'ಸ್ವಾಗತ',
    logout: 'ಲೋಗೌಟ್',
    madeWith: 'ಟೀಮ್ ಬೂಮರ್ಸ್‌ನಿಂದ <3 ನೊಂದಿಗೆ ಮಾಡಲ್ಪಟ್ಟಿದೆ',
    madeByIndians: 'ಭಾರತೀಯರಿಂದ ಭಾರತೀಯರಿಗಾಗಿ ತಯಾರಿಸಲಾಗಿದೆ',
    heroTitle: 'ವೈದ್ಯಕೀಯ ಭವಿಷ್ಯ ಇಲ್ಲಿದೆ.',
    heroSubtitle: 'AI-ಚಾಲಿತ ರೋಗನಿರ್ಣಯ ಮತ್ತು ಔಷಧ ಡೇಟಾಬೇಸ್',
    searchMedicine: 'ಔಷಧ ಹುಡುಕಾಟ',
    adminAccess: 'ನಿರ್ವಾಹಕ ಪ್ರವೇಶ',
    userAccess: 'ಬಳಕೆದಾರ ಪ್ರವೇಶ ಡೆಮೊ',
    googleLogin: 'ಗೂಗಲ್ ಲಾಗಿನ್',
    createAccount: 'ಖಾತೆ ರಚಿಸಿ',
    accessAccount: 'ಖಾತೆ ಪ್ರವೇಶಿಸಿ',
    myPrescriptions: 'ನನ್ನ ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್‌ಗಳು',
    healthHistory: 'ಆರೋಗ್ಯ ಇತಿಹಾಸ',
    savedItems: 'ಉಳಿಸಿದ ಐಟಂಗಳು',
    quickStats: 'ತ್ವರಿತ ಅಂಕಿಅಂಶಗಳು',
    heartRate: 'ಹೃದಯ ಬಡಿತ',
    bloodPressure: 'ರಕ್ತದೊತ್ತಡ',
    nextRefill: 'ಮುಂದಿನ ಮರುಪೂರಣ',
    reschedule: 'ಮರುಹೊಂದಿಸಿ',
    findInfo: 'ಮಾಹಿತಿ, ಡೋಸೇಜ್ ಮತ್ತು ಅಡ್ಡಪರಿಣಾಮಗಳನ್ನು ತಕ್ಷಣವೇ ಹುಡುಕಿ',
    hello: 'ನಮಸ್ಕಾರ',
    healthHub: 'ನಿಮ್ಮ ಆರೋಗ್ಯ ಕೇಂದ್ರ',
    adminDashboard: 'ನಿರ್ವಾಹಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    totalUsers: 'ಒಟ್ಟು ಬಳಕೆದಾರರು',
    activeSessions: 'ಸಕ್ರಿಯ ಸೆಷನ್‌ಗಳು',
    databaseSize: 'ಡೇಟಾಬೇಸ್ ಗಾತ್ರ',
    systemStatus: 'ಸಿಸ್ಟಮ್ ಸ್ಥಿತಿ',
    recentActivity: 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
    quickActions: 'ತ್ವರಿತ ಕ್ರಮಗಳು',
    manageUsers: 'ಬಳಕೆದಾರರನ್ನು ನಿರ್ವಹಿಸಿ',
    editDatabase: 'ಡೇಟಾಬೇಸ್ ಸಂಪಾದಿಸಿ',
    viewReports: 'ವರದಿಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    systemSettings: 'ಸಿಸ್ಟಮ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    philosophyTitle: 'ಪಾರದರ್ಶಕತೆಯು ಆರೋಗ್ಯಕರ ಸಮಾಜದತ್ತ ಮೊದಲ ಹೆಜ್ಜೆ ಎಂದು ನಾವು ನಂಬುತ್ತೇವೆ. ಮೆಡ್‌ಎಐ ಕೇವಲ ಒಂದು ಸಾಧನವಲ್ಲ; ಇದು ವೈದ್ಯಕೀಯ ಜ್ಞಾನವನ್ನು ಪ್ರಜಾಪ್ರಭುತ್ವಗೊಳಿಸುವ ಆಂದೋಲನವಾಗಿದೆ.',
    philosophyLabel: 'ನಮ್ಮ ತತ್ವಶಾಸ್ತ್ರ',
    realWorldExp: 'ನೈಜ-ಪ್ರಪಂಚದ ಅನುಭವ',
    realWorldDesc: 'ನಾವು ನಿಮಗೆ ಕೇವಲ ಡೇಟಾವನ್ನು ತೋರಿಸುವುದಿಲ್ಲ; ನೈಜ-ಪ್ರಪಂಚದ ಕ್ಲಿನಿಕಲ್ ಪ್ರಯೋಗಗಳು ಮತ್ತು ರೋಗಿಗಳ ಫಲಿತಾಂಶಗಳಿಂದ ನಾವು ಸಂದರ್ಭವನ್ನು ಒದಗಿಸುತ್ತೇವೆ.',
    profMentorship: 'ವೃತ್ತಿಪರ ಮಾರ್ಗದರ್ಶನ',
    profDesc: 'ನಿಖರತೆ ಮತ್ತು ವಿಶ್ವಾಸಾರ್ಹತೆಯನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಲು ಉನ್ನತ ವೈದ್ಯಕೀಯ ವೃತ್ತಿಪರರ ಇನ್‌ಪುಟ್‌ನೊಂದಿಗೆ ನಮ್ಮ ವೇದಿಕೆಯನ್ನು ನಿರ್ಮಿಸಲಾಗಿದೆ.',
    comparisonTitle: 'ಸಾಂಪ್ರದಾಯಿಕ VS ಮೆಡ್‌ಎಐ',
    tradLabel: 'ಸಾಂಪ್ರದಾಯಿಕ',
    medaiLabel: 'ಮೆಡ್‌ಎಐ',
    tradPoint1: 'ಅಪಾರದರ್ಶಕ ಬೆಲೆ ಮತ್ತು ಗುಪ್ತ ವೆಚ್ಚಗಳು',
    tradPoint2: 'ಕ್ಲಿನಿಕಲ್ ಡೇಟಾಗೆ ಸೀಮಿತ ಪ್ರವೇಶ',
    tradPoint3: 'ನಿಧಾನಗತಿಯ, ಹಸ್ತಚಾಲಿತ ಹೋಲಿಕೆ ಪ್ರಕ್ರಿಯೆ',
    medaiPoint1: 'ಪ್ರತಿ ಮಾತ್ರೆಯಲ್ಲಿ ಸಂಪೂರ್ಣ ಪಾರದರ್ಶಕತೆ',
    medaiPoint2: 'ಜಾಗತಿಕ ಪ್ರಯೋಗಗಳಿಂದ AI-ಚಾಲಿತ ಒಳನೋಟಗಳು',
    medaiPoint3: 'ನಿಮ್ಮ ಬೆರಳ ತುದಿಯಲ್ಲಿ ತ್ವರಿತ, ನಿಖರವಾದ ಡೇಟಾ',
    searchPlaceholder: 'ಔಷಧಕ್ಕಾಗಿ ಹುಡುಕಿ (ಉದಾಹರಣೆಗೆ, ಪ್ಯಾರಸಿಟಮಾಲ್)...',
    dosage: 'ಡೋಸೇಜ್',
    sideEffects: 'ಅಡ್ಡಪರಿಣಾಮಗಳು',
    interactions: 'ಪರಸ್ಪರ ಕ್ರಿಯೆಗಳು',
    viewDetails: 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    project: 'ಪ್ರಾಜೆಕ್ಟ್',
    status: 'ಸ್ಥಿತಿ',
    active: 'ಸಕ್ರಿಯ',
    scrollToExplore: 'ಅನ್ವೇಷಿಸಲು ಸ್ಕ್ರಾಲ್ ಮಾಡಿ',
    orContinueWith: 'ಅಥವಾ ಇದರೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ',
    newToPlatform: 'ವೇದಿಕೆಗೆ ಹೊಸಬರೇ?',
    alreadyHaveAccount: 'ಈಗಾಗಲೇ ಖಾತೆ ಹೊಂದಿದ್ದೀರಾ?',
    databaseLabel: 'ಡೇಟಾಬೇಸ್',
    accessPortal: 'ಪ್ರವೇಶ ಪೋರ್ಟಲ್',
    databaseDesc: 'ನಮ್ಮ ಸಂಪೂರ್ಣ ವಿಶ್ಲೇಷಣಾತ್ಮಕ ಡೇಟಾಬೇಸ್ ಈಗ ಸಾರ್ವಜನಿಕ ಸಂಶೋಧನೆಗಾಗಿ ಮುಕ್ತವಾಗಿದೆ. ಸಾವಿರಾರು ಬ್ರಾಂಡೆಡ್ ಔಷಧಿಗಳನ್ನು ಅವುಗಳ ಜೆನೆರಿಕ್ ಸಮಾನಗಳೊಂದಿಗೆ ಹೋಲಿಸಿ.',
    readyForAnalysis: 'ವಿಶ್ಲೇಷಣೆಗೆ ಸಿದ್ಧ',
    exploreFullArchive: 'ಪೂರ್ಣ ಆರ್ಕೈವ್ ಅನ್ನು ಅನ್ವೇಷಿಸಿ.',
    enterDatabase: 'ಡೇಟಾಬೇಸ್ ಪ್ರವೇಶಿಸಿ',
    medicines: 'ಔಷಧಿಗಳು',
    verified: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    avgSavings: 'ಸರಾಸರಿ ಉಳಿತಾಯ',
    systemStatusOperational: 'ಸಿಸ್ಟಮ್ ಸ್ಥಿತಿ: ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತಿದೆ',
    copyrightMedAI: '© 2026 ಮೆಡ್‌ಎಐ ವಿಶ್ಲೇಷಣಾತ್ಮಕ ಘಟಕ',
    searchEngine: 'ಸರ್ಚ್ ಇಂಜಿನ್.',
    inputQuery: 'ಇನ್‌ಪುಟ್ ಕ್ವೆರಿ',
    enterMedicineName: 'ಔಷಧಿಯ ಹೆಸರನ್ನು ನಮೂದಿಸಿ...',
    noResultsFound: 'ಡೇಟಾಬೇಸ್‌ನಲ್ಲಿ ಯಾವುದೇ ಫಲಿತಾಂಶಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    readyForAnalysisSearch: 'ವಿಶ್ಲೇಷಣೆಗೆ ಸಿದ್ಧವಾಗಿದೆ',
    selectMedicineToBegin: 'ಪ್ರಾರಂಭಿಸಲು ಸೈಡ್‌ಬಾರ್‌ನಿಂದ ಔಷಧಿಯನ್ನು ಆರಿಸಿ',
    brandedStandard: 'ಬ್ರಾಂಡೆಡ್ ಸ್ಟ್ಯಾಂಡರ್ಡ್',
    genericAlternative: 'ಜೆನೆರಿಕ್ ಪರ್ಯಾಯ',
    verifiedEquivalent: 'ಪರಿಶೀಲಿಸಿದ ಸಮಾನ',
    marketPrice: 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆ',
    ourPrice: 'ನಮ್ಮ ಬೆಲೆ',
    savings: 'ಉಳಿತಾಯ',
    costAnalysis: 'ವೆಚ್ಚದ ವಿಶ್ಲೇಷಣೆ',
    composition: 'ಸಂಯೋಜನೆ',
    molecularStructureIdentical: 'ಆಣ್ವಿಕ ರಚನೆ ಮತ್ತು ಸಕ್ರಿಯ ಪದಾರ್ಥಗಳು ಬ್ರಾಂಡೆಡ್ ಆವೃತ್ತಿಗೆ 100% ಒಂದೇ ಆಗಿರುತ್ತವೆ.',
    generatePrescriptionReport: 'ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ವರದಿಯನ್ನು ರಚಿಸಿ',
    analyticalDatabaseVersion: 'ವಿಶ್ಲೇಷಣಾತ್ಮಕ ಡೇಟಾಬೇಸ್ v2.0',
    description: 'ವಿವರಣೆ',
    switchingTo: 'ಬದಲಾಯಿಸುವುದು',
    savesYouApproximately: 'ನಿಮಗೆ ಸರಿಸುಮಾರು ಉಳಿಸುತ್ತದೆ',
    perUnit: 'ಪ್ರತಿ ಯೂನಿಟ್‌ಗೆ.',
    footerDesc: 'ಆರೋಗ್ಯ ರಕ್ಷಣೆಯಲ್ಲಿ ಪಾರದರ್ಶಕತೆಗೆ ಮೀಸಲಾದ ಯೋಜನೆ. ವೈದ್ಯಕೀಯ ಭವಿಷ್ಯಕ್ಕಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ.',
    navigation: 'ನ್ಯಾವಿಗೇಷನ್',
    socials: 'ಸೋಷಿಯಲ್ಸ್',
    madeInAugust: 'ಮೇಡ್ ಇನ್ ಆಗಸ್ಟ್®',
    operational: 'ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತಿದೆ',
    live: 'ಲೈವ್',
    viewAll: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
    patientRecord: 'ರೋಗಿಯ ದಾಖಲೆ',
    analyzed2HoursAgo: '2 ಗಂಟೆಗಳ ಹಿಂದೆ ವಿಶ್ಲೇಷಿಸಲಾಗಿದೆ',
    aiConfidence: 'AI ವಿಶ್ವಾಸ',
    healthTrendsVisualization: 'ಆರೋಗ್ಯ ಪ್ರವೃತ್ತಿಗಳ ದೃಶ್ಯೀಕರಣ',
    realTimeDataProcessing: 'ನೈಜ-ಸಮಯದ ಡೇಟಾ ಸಂಸ್ಕರಣೆ...',
    upcomingAppointments: 'ಮುಂಬರುವ ನೇಮಕಾತಿಗಳು',
    staffMeeting: 'ಸಿಬ್ಬಂದಿ ಸಭೆ',
    conferenceRoomB: 'ಕಾನ್ಫರೆನ್ಸ್ ರೂಮ್ ಬಿ',
    accessFeature: 'ವೈಶಿಷ್ಟ್ಯವನ್ನು ಪ್ರವೇಶಿಸಿ',
    myPrescriptionsDesc: 'ನಿಮ್ಮ ಪ್ರಸ್ತುತ ಔಷಧಿಗಳು ಮತ್ತು ವೇಳಾಪಟ್ಟಿಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.',
    healthHistoryDesc: 'ನಿಮ್ಮ ಹಿಂದಿನ ರೋಗನಿರ್ಣಯಗಳು ಮತ್ತು ವೈದ್ಯಕೀಯ ವರದಿಗಳನ್ನು ವೀಕ್ಷಿಸಿ.',
    savedItemsDesc: 'ನಿಮ್ಮ ಬುಕ್‌ಮಾರ್ಕ್ ಮಾಡಿದ ಔಷಧಿಗಳು ಮತ್ತು ಲೇಖನಗಳಿಗೆ ತ್ವರಿತ ಪ್ರವೇಶ.',
    generalCheckup: 'ಸಾಮಾನ್ಯ ತಪಾಸಣೆ',
    drSarahJohnson: 'ಡಾ. ಸಾರಾ ಜಾನ್ಸನ್',
    in4Days: '4 ದಿನಗಳಲ್ಲಿ',
  },
  gu: {
    home: 'હોમ',
    philosophy: 'તત્વજ્ઞાન',
    database: 'ડેટાબેઝ',
    search: 'શોધો',
    dashboard: 'ડેશબોર્ડ',
    signin: 'સાઇન ઇન',
    signup: 'સાઇન અપ',
    welcome: 'સ્વાગત છે',
    logout: 'લોગઆઉટ',
    madeWith: 'ટીમ બૂમર્સ દ્વારા <3 સાથે બનાવેલ',
    madeByIndians: 'ભારતીયો દ્વારા ભારતીયો માટે બનાવવામાં આવ્યું છે',
    heroTitle: 'દવાઓનું ભવિષ્ય અહીં છે.',
    heroSubtitle: 'AI-સંચાલિત નિદાન અને દવા ડેટાબેઝ',
    searchMedicine: 'દવા શોધો',
    adminAccess: 'એડમિન એક્સેસ',
    userAccess: 'યુઝર એક્સેસ ડેમો',
    googleLogin: 'ગુગલ લોગિન',
    createAccount: 'ખાતું બનાવો',
    accessAccount: 'ખાતું એક્સેસ કરો',
    myPrescriptions: 'મારા પ્રિસ્ક્રિપ્શન્સ',
    healthHistory: 'આરોગ્ય ઇતિહાસ',
    savedItems: 'સાચવેલી વસ્તુઓ',
    quickStats: 'ઝડપી આંકડા',
    heartRate: 'હૃદયના ધબકારા',
    bloodPressure: 'બ્લડ પ્રેશર',
    nextRefill: 'આગામી રિફિલ',
    reschedule: 'ફરીથી શેડ્યૂલ કરો',
    findInfo: 'માહિતી, ડોઝ અને આડઅસરો તરત જ શોધો',
    hello: 'નમસ્તે',
    healthHub: 'તમારું આરોગ્ય કેન્દ્ર',
    adminDashboard: 'એડમિન ડેશબોર્ડ',
    totalUsers: 'કુલ વપરાશકર્તાઓ',
    activeSessions: 'સક્રિય સત્રો',
    databaseSize: 'ડેટાબેઝ કદ',
    systemStatus: 'સિસ્ટમ સ્થિતિ',
    recentActivity: 'તાજેતરની પ્રવૃત્તિ',
    quickActions: 'ઝડપી ક્રિયાઓ',
    manageUsers: 'વપરાશકર્તાઓ મેનેજ કરો',
    editDatabase: 'ડેટાબેઝ સંપાદિત કરો',
    viewReports: 'રિપોર્ટ્સ જુઓ',
    systemSettings: 'સિસ્ટમ સેટિંગ્સ',
    philosophyTitle: 'અમારું માનવું છે કે પારદર્શિતા એ સ્વસ્થ સમાજ તરફનું પ્રથમ પગલું છે. મેડએઆઈ માત્ર એક સાધન નથી; તે તબીબી જ્ઞાનના લોકશાહીકરણ માટેનું આંદોલન છે.',
    philosophyLabel: 'અમારી ફિલોસોફી',
    realWorldExp: 'વાસ્તવિક દુનિયાનો અનુભવ',
    realWorldDesc: 'અમે તમને માત્ર ડેટા બતાવતા નથી; અમે વાસ્તવિક દુનિયાના ક્લિનિકલ ટ્રાયલ્સ અને દર્દીના પરિણામોમાંથી સંદર્ભ પ્રદાન કરીએ છીએ.',
    profMentorship: 'વ્યાવસાયિક માર્ગદર્શન',
    profDesc: 'ચોકસાઈ અને વિશ્વસનીયતા સુનિશ્ચિત કરવા માટે અમારું પ્લેટફોર્મ ટોચના તબીબી વ્યાવસાયિકોના ઇનપુટ સાથે બનાવવામાં આવ્યું છે.',
    comparisonTitle: 'પરંપરાગત VS મેડએઆઈ',
    tradLabel: 'પરંપરાગત',
    medaiLabel: 'મેડએઆઈ',
    tradPoint1: 'અપારદર્શક કિંમત અને છુપાયેલા ખર્ચ',
    tradPoint2: 'ક્લિનિકલ ડેટાની મર્યાદિત ઍક્સેસ',
    tradPoint3: 'ધીમી, મેન્યુઅલ સરખામણી પ્રક્રિયા',
    medaiPoint1: 'દરેક ગોળીમાં સંપૂર્ણ પારદર્શિતા',
    medaiPoint2: 'વૈશ્વિક ટ્રાયલ્સમાંથી AI-સંચાલિત આંતરદૃષ્ટિ',
    medaiPoint3: 'તમારી આંગળીના ટેરવે ત્વરિત, સચોટ ડેટા',
    searchPlaceholder: 'દવા શોધો (દા.ત., પેરાસીટામોલ)...',
    dosage: 'ડોઝ',
    sideEffects: 'આડઅસરો',
    interactions: 'પરસ્પર ક્રિયાઓ',
    viewDetails: 'વિગતો જુઓ',
    project: 'પ્રોજેક્ટ',
    status: 'સ્થિતિ',
    active: 'સક્રિય',
    scrollToExplore: 'અન્વેષણ કરવા માટે સ્ક્રોલ કરો',
    orContinueWith: 'અથવા સાથે ચાલુ રાખો',
    newToPlatform: 'પ્લેટફોર્મ પર નવા છો?',
    alreadyHaveAccount: 'પહેલેથી જ એકાઉન્ટ છે?',
    databaseLabel: 'ડેટાબેઝ',
    accessPortal: 'એક્સેસ પોર્ટલ',
    databaseDesc: 'અમારો સંપૂર્ણ વિશ્લેષણાત્મક ડેટાબેઝ હવે જાહેર સંશોધન માટે ખુલ્લો છે. હજારો બ્રાન્ડેડ દવાઓની તેમના જેનરિક સમકક્ષો સાથે સરખામણી કરો.',
    readyForAnalysis: 'વિશ્લેષણ માટે તૈયાર',
    exploreFullArchive: 'સંપૂર્ણ આર્કાઇવનું અન્વેષણ કરો.',
    enterDatabase: 'ડેટાબેઝમાં પ્રવેશો',
    medicines: 'દવાઓ',
    verified: 'ચકાસાયેલ',
    avgSavings: 'સરેરાશ બચત',
    systemStatusOperational: 'સિસ્ટમ સ્થિતિ: કાર્યરત',
    copyrightMedAI: '© 2026 મેડએઆઈ વિશ્લેષણાત્મક એકમ',
    searchEngine: 'સર્ચ એન્જિન.',
    inputQuery: 'ઇનપુટ ક્વેરી',
    enterMedicineName: 'દવાનું નામ દાખલ કરો...',
    noResultsFound: 'ડેટાબેઝમાં કોઈ પરિણામ મળ્યા નથી',
    readyForAnalysisSearch: 'વિશ્લેષણ માટે તૈયાર',
    selectMedicineToBegin: 'શરૂ કરવા માટે સાઇડબારમાંથી દવા પસંદ કરો',
    brandedStandard: 'બ્રાન્ડેડ સ્ટાન્ડર્ડ',
    genericAlternative: 'જેનેરિક વિકલ્પ',
    verifiedEquivalent: 'ચકાસાયેલ સમકક્ષ',
    marketPrice: 'બજાર કિંમત',
    ourPrice: 'અમારી કિંમત',
    savings: 'બચત',
    costAnalysis: 'ખર્ચ વિશ્લેષણ',
    composition: 'બંધારણ',
    molecularStructureIdentical: 'આણ્વિક સંરચના અને સક્રિય ઘટકો બ્રાન્ડેડ સંસ્કરણ સાથે 100% સમાન છે.',
    generatePrescriptionReport: 'પ્રિસ્ક્રિપ્શન રિપોર્ટ જનરેટ કરો',
    analyticalDatabaseVersion: 'વિશ્લેષણાત્મક ડેટાબેઝ v2.0',
    description: 'વર્ણન',
    switchingTo: 'પર સ્વિચ કરવું',
    savesYouApproximately: 'તમને આશરે બચાવે છે',
    perUnit: 'યુનિટ દીઠ.',
    footerDesc: 'આરોગ્ય સંભાળમાં પારદર્શિતા માટે સમર્પિત પ્રોજેક્ટ. દવાના ભવિષ્ય માટે બનાવવામાં આવ્યું છે.',
    navigation: 'નેવિગેશન',
    socials: 'સોશિયલ',
    madeInAugust: 'મેડ ઇન ઓગસ્ટ®',
    operational: 'કાર્યરત',
    live: 'લાઇવ',
    viewAll: 'બધું જુઓ',
    patientRecord: 'દર્દીનો રેકોર્ડ',
    analyzed2HoursAgo: '2 કલાક પહેલા વિશ્લેષણ કરવામાં આવ્યું',
    aiConfidence: 'AI આત્મવિશ્વાસ',
    healthTrendsVisualization: 'આરોગ્ય વલણો વિઝ્યુલાઇઝેશન',
    realTimeDataProcessing: 'રીઅલ-ટાઇમ ડેટા પ્રોસેસિંગ...',
    upcomingAppointments: 'આગામી એપોઇન્ટમેન્ટ્સ',
    staffMeeting: 'સ્ટાફ મીટિંગ',
    conferenceRoomB: 'કોન્ફરન્સ રૂમ બી',
    accessFeature: 'એક્સેસ ફીચર',
    myPrescriptionsDesc: 'તમારી વર્તમાન દવાઓ અને સમયપત્રકનો ટ્રૅક રાખો.',
    healthHistoryDesc: 'તમારા ભૂતકાળના નિદાન અને તબીબી અહેવાલો જુઓ.',
    savedItemsDesc: 'તમારી બુકમાર્ક કરેલી દવાઓ અને લેખોની ઝડપી ઍક્સેસ.',
    generalCheckup: 'સામાન્ય ચેકઅપ',
    drSarahJohnson: 'ડો. સારા જોહ્ન્સન',
    in4Days: '4 દિવસમાં',
  },
  bn: {
    home: 'হোম',
    philosophy: 'দর্শন',
    database: 'ডেটাবেস',
    search: 'অনুসন্ধান',
    dashboard: 'ড্যাশবোর্ড',
    signin: 'সাইন ইন',
    signup: 'সাইন আপ',
    welcome: 'স্বাগতম',
    logout: 'লগআউট',
    madeWith: 'টিম বুমারস দ্বারা <3 দিয়ে তৈরি',
    madeByIndians: 'ভারতীয়দের দ্বারা ভারতীয়দের জন্য তৈরি',
    heroTitle: 'চিকিৎসার ভবিষ্যৎ এখানে।',
    heroSubtitle: 'AI-চালিত রোগ নির্ণয় এবং ঔষধ ডেটাবেস',
    searchMedicine: 'ঔষধ অনুসন্ধান',
    adminAccess: 'অ্যাডমিন অ্যাক্সেস',
    userAccess: 'ইউজার অ্যাক্সেস ডেমো',
    googleLogin: 'গুগল লগইন',
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    accessAccount: 'অ্যাকাউন্ট অ্যাক্সেস করুন',
    myPrescriptions: 'আমার প্রেসক্রিপশন',
    healthHistory: 'স্বাস্থ্য ইতিহাস',
    savedItems: 'সংরক্ষিত আইটেম',
    quickStats: 'দ্রুত পরিসংখ্যান',
    heartRate: 'হৃৎস্পন্দন',
    bloodPressure: 'রক্তচাপ',
    nextRefill: 'পরবর্তী রিফিল',
    reschedule: 'পুনরায় নির্ধারণ করুন',
    findInfo: 'তথ্য, ডোজ এবং পার্শ্ব প্রতিক্রিয়া অবিলম্বে খুঁজুন',
    hello: 'হ্যালো',
    healthHub: 'আপনার স্বাস্থ্য কেন্দ্র',
    adminDashboard: 'অ্যাডমিন ড্যাশবোর্ড',
    totalUsers: 'মোট ব্যবহারকারী',
    activeSessions: 'সক্রিয় সেশন',
    databaseSize: 'ডেটাবেস আকার',
    systemStatus: 'সিস্টেম স্ট্যাটাস',
    recentActivity: 'সাম্প্রতিক কার্যকলাপ',
    quickActions: 'দ্রুত পদক্ষেপ',
    manageUsers: 'ব্যবহারকারী পরিচালনা করুন',
    editDatabase: 'ডেটাবেস সম্পাদনা করুন',
    viewReports: 'রিপোর্ট দেখুন',
    systemSettings: 'সিস্টেম সেটিংস',
    philosophyTitle: 'আমরা বিশ্বাস করি যে স্বচ্ছতা একটি স্বাস্থ্যকর সমাজের দিকে প্রথম পদক্ষেপ। মেডএআই কেবল একটি সরঞ্জাম নয়; এটি চিকিৎসা জ্ঞানকে গণতান্ত্রিক করার একটি আন্দোলন।',
    philosophyLabel: 'আমাদের দর্শন',
    realWorldExp: 'বাস্তব বিশ্বের অভিজ্ঞতা',
    realWorldDesc: 'আমরা আপনাকে কেবল ডেটা দেখাই না; আমরা বাস্তব বিশ্বের ক্লিনিকাল ট্রায়াল এবং রোগীর ফলাফল থেকে প্রসঙ্গ সরবরাহ করি।',
    profMentorship: 'পেশাদার মেন্টরশিপ',
    profDesc: 'নির্ভুলতা এবং নির্ভরযোগ্যতা নিশ্চিত করতে আমাদের প্ল্যাটফর্মটি শীর্ষ চিকিৎসা পেশাদারদের ইনপুট দিয়ে তৈরি করা হয়েছে।',
    comparisonTitle: 'ঐতিহ্যগত বনাম মেডএআই',
    tradLabel: 'ঐতিহ্যগত',
    medaiLabel: 'মেডএআই',
    tradPoint1: 'অস্বচ্ছ মূল্য নির্ধারণ এবং লুকানো খরচ',
    tradPoint2: 'ক্লিনিকাল ডেটাতে সীমিত অ্যাক্সেস',
    tradPoint3: 'ধীর, ম্যানুয়াল তুলনা প্রক্রিয়া',
    medaiPoint1: 'প্রতিটি বড়িতে সম্পূর্ণ স্বচ্ছতা',
    medaiPoint2: 'বৈশ্বিক ট্রায়াল থেকে AI-চালিত অন্তর্দৃষ্টি',
    medaiPoint3: 'আপনার নখদর্পণে তাৎক্ষণিক, নির্ভুল ডেটা',
    searchPlaceholder: 'ঔষধ খুঁজুন (যেমন, প্যারাসিটামল)...',
    dosage: 'ডোজ',
    sideEffects: 'পার্শ্ব প্রতিক্রিয়া',
    interactions: 'পারস্পরিক ক্রিয়া',
    viewDetails: 'বিস্তারিত দেখুন',
    project: 'প্রকল্প',
    status: 'অবস্থা',
    active: 'সক্রিয়',
    scrollToExplore: 'অন্বেষণ করতে স্ক্রোল করুন',
    orContinueWith: 'অথবা দিয়ে চালিয়ে যান',
    newToPlatform: 'প্ল্যাটফর্মে নতুন?',
    alreadyHaveAccount: 'ইতিমধ্যে একটি অ্যাকাউন্ট আছে?',
    databaseLabel: 'ডেটাবেস',
    accessPortal: 'অ্যাক্সেস পোর্টাল',
    databaseDesc: 'আমাদের সম্পূর্ণ বিশ্লেষণাত্মক ডেটাবেস এখন জনসাধারণের গবেষণার জন্য উন্মুক্ত। হাজার হাজার ব্র্যান্ডেড ওষুধের সাথে তাদের জেনেরিক সমতুল্য তুলনা করুন।',
    readyForAnalysis: 'বিশ্লেষণের জন্য প্রস্তুত',
    exploreFullArchive: 'সম্পূর্ণ আর্কাইভ অন্বেষণ করুন।',
    enterDatabase: 'ডেটাবেসে প্রবেশ করুন',
    medicines: 'ওষুধ',
    verified: 'যাচাইকৃত',
    avgSavings: 'গড় সাশ্রয়',
    systemStatusOperational: 'সিস্টেম স্ট্যাটাস: সচল',
    copyrightMedAI: '© 2026 মেডএআই বিশ্লেষণাত্মক ইউনিট',
    searchEngine: 'সার্চ ইঞ্জিন।',
    inputQuery: 'ইনপুট কোয়েরি',
    enterMedicineName: 'ওষুধের নাম লিখুন...',
    noResultsFound: 'ডেটাবেসে কোনো ফলাফল পাওয়া যায়নি',
    readyForAnalysisSearch: 'বিশ্লেষণের জন্য প্রস্তুত',
    selectMedicineToBegin: 'শুরু করতে সাইডবার থেকে একটি ওষুধ নির্বাচন করুন',
    brandedStandard: 'ব্র্যান্ডেড স্ট্যান্ডার্ড',
    genericAlternative: 'জেনেরিক বিকল্প',
    verifiedEquivalent: 'যাচাইকৃত সমতুল্য',
    marketPrice: 'বাজার মূল্য',
    ourPrice: 'আমাদের মূল্য',
    savings: 'সঞ্চয়',
    costAnalysis: 'ব্যয় বিশ্লেষণ',
    composition: 'গঠন',
    molecularStructureIdentical: 'আণবিক গঠন এবং সক্রিয় উপাদানগুলি ব্র্যান্ডেড সংস্করণের সাথে ১০০% অভিন্ন।',
    generatePrescriptionReport: 'প্রেসক্রিপশন রিপোর্ট তৈরি করুন',
    analyticalDatabaseVersion: 'বিশ্লেষণাত্মক ডেটাবেস v2.0',
    description: 'বর্ণনা',
    switchingTo: 'সুইচ করা হচ্ছে',
    savesYouApproximately: 'আপনাকে প্রায় সাশ্রয় করে',
    perUnit: 'প্রতি ইউনিট।',
    footerDesc: 'স্বাস্থ্যসেবায় স্বচ্ছতার জন্য নিবেদিত একটি প্রকল্প। চিকিৎসার ভবিষ্যতের জন্য নির্মিত।',
    navigation: 'নেভিগেশন',
    socials: 'সোশ্যাল',
    madeInAugust: 'মেড ইন আগস্ট®',
    operational: 'সচল',
    live: 'লাইভ',
    viewAll: 'সব দেখুন',
    patientRecord: 'রোগীর রেকর্ড',
    analyzed2HoursAgo: '২ ঘণ্টা আগে বিশ্লেষণ করা হয়েছে',
    aiConfidence: 'এআই আত্মবিশ্বাস',
    healthTrendsVisualization: 'স্বাস্থ্য প্রবণতা ভিজ্যুয়ালাইজেশন',
    realTimeDataProcessing: 'রিয়েল-টাইম ডেটা প্রসেসিং...',
    upcomingAppointments: 'আসন্ন অ্যাপয়েন্টমেন্ট',
    staffMeeting: 'স্টাফ মিটিং',
    conferenceRoomB: 'কনফারেন্স রুম বি',
    accessFeature: 'অ্যাক্সেস ফিচার',
    myPrescriptionsDesc: 'আপনার বর্তমান ওষুধ এবং সময়সূচী ট্র্যাক রাখুন।',
    healthHistoryDesc: 'আপনার অতীতের রোগ নির্ণয় এবং চিকিৎসা রিপোর্ট দেখুন।',
    savedItemsDesc: 'আপনার বুকমার্ক করা ওষুধ এবং নিবন্ধগুলিতে দ্রুত অ্যাক্সেস।',
    generalCheckup: 'সাধারণ চেকআপ',
    drSarahJohnson: 'ডাঃ সারা জনসন',
    in4Days: '৪ দিনের মধ্যে',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<LanguageType>('en');

  const t = (key: string) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
